# Generated by Django 3.0.3 on 2020-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twats', '0002_auto_20200428_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
