# Generated by Django 3.0.3 on 2020-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twats', '0003_auto_20200601_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
